public enum PlayerState
{
    Unknown,
    NotPlaying,
    Gameplay_Loading,
    Gameplay_ReadyToStart,
    Gameplay_Playing,
    SelectSong,
    PlayerJoin_SelectProfile,
    PlayerJoin_CreateProfile,
    PlayerJoin_Options,
    PlayerJoin_Ready,
    DifficultySelect_Selecting,
    DifficultySelect_Ready,
    DifficultySelect_ConfirmNerf,
    DifficultySelect_ConfirmDisconnect,
    Evaluation_NotReady,
    Evaluation_Ready
}
